### ISSUE TITLE
Pedalpalooza data sometimes appears on the "Add event" page

### ISSUE THREAD

**Issue by OneHwang** [Shift2Bikes/shiftcal#138] opened 2018-01-20 23:52 UTC
When users click on the "Pedalpalooza" heading then "Add event" immediately after, events during Pedalpalooza are appended to the "Add event" page

**Comment by carrythebanner** [comment] 2018-05-07 05:41
I tried repeatedly but I couldn't reproduce this. Either it's been fixed in the interim, or I'm not taking the exact steps needed to repro.

**Closed** 2018-05-19 02:05 UTC
Labels: bug
